### ISSUE TITLE
To use CSP directive keywords unsafe-inline and unsafe-eval, you specify the inline and eval values respectively

### ISSUE THREAD

**Issue by nchelluri** [twitter/secureheaders#169]
It would make more sense, to me, to specify `unsafe-inline` and `unsafe-eval` instead.

Some minor details available in this Twitter conversation: https://twitter.com/narsimham/status/647190150301093888 - including that this seems to be an historical artifact of browsers using different directive keywords to achieve the same function.

Just to cover all bases I will mention that changing this behavior may warrant a semantic versioning major version bump.

**Comment by oreoshake** [comment]
As discussed via twitter, I fully support this change. It is nothing but a relic of the days with `x-webkit-csp` and `x-content-security-policy` had different values for the same meaning.

However, I'm not sure I want to break older code in the next major version bump. Or at the very least, I want to raise a specific exception with a detailed explanation on how to fix it at boot time instead of just a deprecation / install message.
