### ISSUE TITLE
When will 3.0.0 be released?

### ISSUE THREAD

**Issue by david-a-wheeler** [twitter/secureheaders#210]
This gem looks awesome, but I usually wait until there's an official "it's released" announcement from the project, and I then get the gem from RubyGems.  I looked on <https://rubygems.org/gems/secure_headers> and saw that 3.0.0.pre2 was posted December 22, 2015... but no actual 3.0.0.

Any idea when you'll declare victory and release 3.0.0?  I couldn't figure out from the issue tracker what the blockers were (if any).

I'm hoping to become a new user :-).

Thanks!

**Comment by oreoshake** [comment]
Hi @david-a-wheeler,

Thanks for the interest. I am getting ready to pull the trigger, but I'm being extra cautious since this is such a significant rewrite. Some of the design is still being hammered out and may change soon.

Specifically we came across an issue where the protocol stripping (not present in the 2.x line) is causing an issue on safari (:fire: :hocho: :skull:) because safari's CSP support is terrible.

**Comment by oreoshake** [comment]
Not sure if you're following along but I just merged a few branches and pushed 3.0.0.pre3 to rubygems. I anticipate this will be the last pre release unless any bugs are uncovered but I want to let this version bake a little while.

**Comment by david-a-wheeler** [comment]
Thanks! I am looking forward to it!

**Comment by oreoshake** [comment]
:boom: https://github.com/twitter/secureheaders/releases/tag/v3.0.0 https://rubygems.org/gems/secure_headers/versions/3.0.0 :boom:

**Comment by david-a-wheeler** [comment]
Congrats!!
