### ISSUE TITLE
Rails with an ember-cli route

### ISSUE THREAD

**Issue by jcward10** [twitter/secureheaders#234]
The rails secure headers complete blocks the ember js. I tried to `SecureHeaders.opt_out_of_all_protection(request)` for that controller action. However, it breaks on another module loading becuase it is trying to use nonced_javascript_tag. This results in a `Attempted to override an opt-out CSP config.` error. Is there a check for the opt-out option that we can use to use a plain javascript_tag if the opt_out is set?

**Comment by jcward10** [comment]
I think I figured it out. I used and after_action callback to opt_out_of_all_protection

**Comment by oreoshake** [comment]
It is certainly possible to configure CSP to be compatible with ember and keeping CSP around would fix the issue you ran into. If you look at the developer console on the page with errors, it will pretty much tell you what you need to add to your CSP configuration.

**Comment by jcward10** [comment]
So I don't have to disable it and for the rails action for the ember app and use https://github.com/rwjblue/ember-cli-content-security-policy/ ?

**Comment by oreoshake** [comment]
I don't think I understand how your app works. https://github.com/rwjblue/ember-cli-content-security-policy/ affects express servers, secure_headers affects ruby servers. So if you're having to opt out, then I would think https://github.com/rwjblue/ember-cli-content-security-policy/ would have no effect since it sounds like you're using ruby application code to serve the page.
