### ISSUE TITLE
Removing http schemes

### ISSUE THREAD

**Issue by davidhan527** [twitter/secureheaders#251]
I noticed that the http schemes are being stripped when using version 3.X for csp. Why was this change made? It would help if this is also mentioned in the upgrade path since any tests that check the csp header value will break based on this change.

**Comment by reedloden** [comment]
This is likely due to `preserve_schemes: false` being the default now. If you change that to `true`, I suspect things will go back to what you expect.

**Comment by oreoshake** [comment]
This change was made because the need to preserve schemes implies that you have mixed content. A source without a scheme defaults to the current scheme and allows "upgrades". ["Mixed was a mistake" which is why the default is to not support it](https://twitter.com/annevk/status/723718488318181376). As @reedloden mentions, `true` will add the schemes back. 

Added to the upgrade doc: https://github.com/twitter/secureheaders/commit/e8f51038759fd4ad71cf4a3815ac4a68105b9e8e

**Comment by davidhan527** [comment]
Got it. Thank you for the explanation.
