### ISSUE TITLE
Setting nonce in csp

### ISSUE THREAD

**Issue by davidhan527** [twitter/secureheaders#254]
Previously if we had the keyword 'nonce' in our csp configuration it would automatically set the generated nonce in the headers but now it no longer seems to work after upgrading to 3.2 

`script_src: %w('self' 'nonce')`

This is what I get when I inspect the header.
![image](https://cloud.githubusercontent.com/assets/4370987/15117777/15c6d0c4-15d7-11e6-824a-67412a18d4ad.png)

**Comment by oreoshake** [comment]
The way nonces are managed has changed in 3.x as you can tell. Please follow the instructions in the [README](https://github.com/twitter/secureheaders#nonce).

Specifically, `nonce` is no longer a source expression. Using the view helpers is the recommended way of using csp nonce (and works in 2.x and 3.x).

Let me know if you have any more questions, otherwise close this out?

**Comment by davidhan527** [comment]
Oh I see. We should also add that to the upgrade notes since it's a bit unclear that we no longer need nonce as a source attribute anymore.

Thanks again! Appreciate the help.
