### ISSUE TITLE
Android 4.4 unsupported nonces

### ISSUE THREAD

**Issue by jasssonpet** [twitter/secureheaders#381]
# Bugs

Using a script with added `content_security_policy_script_nonce` tag is not being executed on stock Android 4.4 device and emulator (in stock browser and webview). The same script is loaded on Android 4.2/4.3.

I've tried manually passing `'unsafe-inline'` instead and the script was loaded.

User-Agents:
```
Mozilla/5.0 (Linux; Android 4.4.2; Android SDK built for x86 Build/KK) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 4.4.4; XT1021 Build/KXC21.5-40) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36
```

### Expected outcome

The script should be executed.

### Actual outcome

Script with nonce is blocked. The following logs are produced:
```
01-19 12:45:47.009 2241-2241/com.android.browser E/browser: Console: The source list for Content Security Policy directive 'script-src' contains an invalid source: ''nonce-VqttPDPhtEDgC+kNL57SmLkTpCzD+6bPDh2TbhrROJg=''. It will be ignored. :0
01-19 12:45:47.009 2241-2241/com.android.browser E/browser: Console: Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-VqttPDPhtEDgC+kNL57SmLkTpCzD+6bPDh2TbhrROJg='".
```

### Config

Using version 5.0.4:
```ruby
SecureHeaders::Configuration.configure do |config|
  config.csp = {
    :default_src => SecureHeaders::OPT_OUT,
    :script_src => %w('self')
  }
  config.hsts = SecureHeaders::OPT_OUT
  config.x_download_options = SecureHeaders::OPT_OUT
  config.x_frame_options = SecureHeaders::OPT_OUT
  config.x_permitted_cross_domain_policies = SecureHeaders::OPT_OUT
end
```
### Generated headers

```
Content-Security-Policy: script-src 'self' 'nonce-VqttPDPhtEDgC+kNL57SmLkTpCzD+6bPDh2TbhrROJg='
```

**Comment by oreoshake** [comment]
Is the nonce added to the DOM? 

I’m not sure secure_headers knows that android supports minces so using that helper *should* instead add ‘unsafe-inline’. 

We may have two bugs: if android supports bounces, we should whitelist it to use them. And when using a nonce on unsupported browsers should automatically add ‘unsafe-inline’. 

It’s been over a year since I’ve used nonces so I forget where this implementation landed. 

(Triaging from :phone:, details are pulled only from my memory)

**Comment by jasssonpet** [comment]
Hello, yes - there is a `nonce` attribute on the script element.

It seems that 4.4 is the first version of Android that uses Chrome as default for webviews and browser engine. This seems to explain why the script was being executed in older Android versions. I assume that `unsafe-inline` was passed as the user agent seemed to pretend for an old Safari. I've just checked and Android 5.0 seems to come with Chrome 37 that has nonce support.

Here is a little snippet that I used to reproduce the issue on Android 4.4:
```html
<meta http-equiv="Content-Security-Policy" content="script-src 'nonce-static'">
<script nonce="static">
console.log('Test');
</script>
```
It looks that nonces are just not supported in these old Chrome versions and `unsafe-inline` looks like a good fallback if it could be detected by secureheaders.

It's a shame that Android 4.4 has still around 15% market share<sup>[1]</sup> as of now but it would be nice if it could be supported.

[1] https://developer.android.com/about/dashboards/index.html

**Comment by oreoshake** [comment]
Yeah, this definitely warrants a fix. 

The percentage of traffic that doesn't not supports nonces is dwindling. Plus we can always use `nonce-asdf` + `'unsafe-inline'` together since it's backwards compatible. Maybe we stop sniffing UA support and send the nonce+unsafe-inline unconditionally.

It might result in warnings to consoles but I think user agents have mostly moved away from that.
